-- ─────────────────────────────────────────────────────────────────────────────
-- 드림아이티비즈(rest06) 스키마 — 공유 Supabase 프로젝트, rest06_ 접두사
-- Supabase SQL Editor 에서 실행. 구글·카카오 로그인은 auth.users 를 그대로 사용.
-- ─────────────────────────────────────────────────────────────────────────────

-- 회원 프로필 (OAuth 최초 로그인 시 upsert)
create table if not exists rest06_profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text,
  name         text,
  avatar       text,
  provider     text,
  streak_days  integer not null default 1,   -- 연속 학습일 (로그인 시 갱신)
  last_active  date,                          -- 마지막 접속일 (스트릭 계산용)
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
-- 기존 테이블이 있으면 컬럼만 추가
alter table rest06_profiles add column if not exists streak_days integer not null default 1;
alter table rest06_profiles add column if not exists last_active date;

-- 결제 내역 (아임포트/PortOne)
create table if not exists rest06_payments (
  id          bigint generated by default as identity primary key,
  payment_id  text unique not null,
  user_id     uuid references auth.users(id) on delete set null,
  email       text,
  course_id   text not null,
  order_name  text,
  amount      integer not null default 0,
  pay_method  text,
  status      text not null default 'pending',   -- pending | paid | test | failed | refunded
  created_at  timestamptz not null default now()
);

-- 수강신청 (강의 등록 상태)
create table if not exists rest06_enrollments (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) on delete cascade,
  email       text,
  course_id   text not null,
  payment_id  text,
  status      text not null default 'pending',    -- pending | active | trial | cancelled
  progress    integer not null default 0,         -- 진도율 0~100
  created_at  timestamptz not null default now(),
  unique (user_id, course_id)
);
alter table rest06_enrollments add column if not exists progress integer not null default 0;

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table rest06_profiles    enable row level security;
alter table rest06_payments    enable row level security;
alter table rest06_enrollments enable row level security;

-- 프로필: 본인 것만 읽기/쓰기
create policy "rest06_profiles_self" on rest06_profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

-- 결제: 본인 것만 조회/생성
create policy "rest06_payments_select" on rest06_payments
  for select using (auth.uid() = user_id);
create policy "rest06_payments_insert" on rest06_payments
  for insert with check (auth.uid() = user_id or user_id is null);

-- 수강신청: 본인 것만 조회/생성/수정
create policy "rest06_enrollments_select" on rest06_enrollments
  for select using (auth.uid() = user_id);
create policy "rest06_enrollments_upsert" on rest06_enrollments
  for insert with check (auth.uid() = user_id or user_id is null);
create policy "rest06_enrollments_update" on rest06_enrollments
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
